### ISSUE TITLE
Can you public the datasets ?

### ISSUE THREAD

**Issue by Doanhdz** [CVRL/RaspberryPiOpenSourceIris#2]

**Comment by zfang399** [comment]
Hi @Doanhdz thanks for your interest in our work.

We are working on releasing the NDIris3D dataset. Please contact Prof. Adam Czajka (acajka@nd.edu) for more details on the progress.

In the mean time, a similar dataset (with photometric pairs) can be requested here (https://cvrl.nd.edu/projects/data/). Please follow the instructions on top of the website.

I hope this helps.

**Comment by Doanhdz** [comment]
Thanks for your reply i will try t download some of these datasets !

**Comment by zfang399** [comment]
Sounds good. I'm closing this issue. Feel free to add new comments / open a new issue if you run into any other problems
