### ISSUE TITLE
Can't open the pre-trained model

### ISSUE THREAD

**Issue by LuckyLeeee** [CVRL/RaspberryPiOpenSourceIris#3]
I can't open the pre-trained model with tensorflow 2.5. I have changed a few things like the ```io.gfile``` and ```compat.v1.GraphDef()``` but no luck. It's always pop up the error: ```RuntimeWarning: Unexpected end-group tag: Not all data was converted```. I wonder maybe It's because of your pre-trained model was corrputed when moving from one place to another?
```
import tensorflow as tf

with tf.io.gfile.GFile('./model/saved_model.pb', "rb") as f:
    graph_def = tf.compat.v1.GraphDef()
    graph_def.ParseFromString(f.read())

print('Check out the input placeholders:')
nodes = [n.name + '=>' + n.op for n in graph_def.node]
for node in nodes:
    print(node)
```

**Comment by zfang399** [comment]
Hi, thanks for your interest in our work! 

Sorry that I don't have alternative pre-trained checkpoints since I no longer have access to the machine on which this project is developed.

Have you tried using tf1 instead of the compat option from tf2? iirc we were using tf1 for the project. The model might be able to be correctly loaded if you try tf1.

**Comment by LuckyLeeee** [comment]
Thank you, I will try using tf1. I have just converted your network code to tensorflow-keras model and got some really good segmentation result but I don't know how to do localization after that. I'm really new in "Iris recognition" so I wonder if I can email you and ask some questions about your project?

**Comment by zfang399** [comment]
Sure, feel free to shoot me an email at zfang399@gmail.com!

**Comment by LuckyLeeee** [comment]
Thank, I will email you. And for the issue, I have successful convert your code to tensorflow model so I will close this. Thank again.
